# Generated by Django 5.0 on 2023-12-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
